### ISSUE TITLE
#include <myAP.h>

### ISSUE THREAD

**Issue by ru-sh** [pvvx/RtlDuino#4]
As far as I understand, I have to create the file manually, but installation instructions don't say anything about it.
Where do I need to create it?

**Comment by ru-sh** [comment]
And, in general, installation instruction doesn't work with Arduino client 1.8+.
boards.txt has to be on the second level into 'hardware' folder (hardware/development/rtl87xx/).

**Comment by daiwallll** [comment]
Hi:
1- add de **preference** into the arduino ide  [https://github.com/Ameba8195/Arduino/raw/master/release/package_realtek.com_ameba_index.json]
and **click ok** .
2- tools->board manager -> search ameba -> install ameba -> close arduino ide .
3- go to the arduino install folder (in my case  c:/program files x86 / arduino)  and open -> hardware -> an there you have to paste the folder call DEVELOPMENT (first you have to dowload the zip or clone) inside the folder development exist other called rtl87xx , and boila

**Comment by gitcnd** [comment]
I think that file just defines your SSID and Password (and does a #DEFINE on `_MYAPCFG_H_`).

Comment out the #include, and fill in the missing bits:-

#ifndef `_MYAPCFG_H_`
char ssid[] =  "yourNetwork";     //  your network SSID (name)
char pass[] = "secretPassword";  // your network password
#endif
